apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.name" . }}
  labels:
    app: {{ include "helm.name" . }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        resources:
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}

        livenessProbe:
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          port: {{ .Values.deployment.livenessProbe.port }}
          path: {{ .Values.deployment.livenessProbe.path }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          port: {{ .Values.deployment.readinessProbe.port }}
          path: {{ .Values.deployment.readinessProbe.path }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}


