# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


deployment:
  replicas: 1

  image: dkr.ecr.eu-west-1.amazonaws.com/sre-challenge
  tag: latest


  containerPort: 8080
  resources: 
    limits:
      cpu: 100m
      memory: 240Mi
    requests:
      cpu: 100m
      memory: 120Mi

  livenessProbe:
    initialDelaySeconds: 5
    port: 8080
    path: /hello

  readinessProbe:
    initialDelaySeconds: 5
    port: 8080
    path: /hello

service:
  ports:
    port: 80
    targetPort: 8080
  type: ClusterIP

ingress:
  paths:
    - /hello